//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""19ef09f4-2ce7-45ae-8825-6fd6d7797642"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4e0ce2a5-d27a-4a15-9bbe-93d8c0d65dab"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drift"",
                    ""type"": ""Button"",
                    ""id"": ""38094ac4-0822-47bf-b3e9-aa84f60ebd41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""b78d1115-039a-4c72-b17a-750d03f296fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""572362ae-6a97-4ed2-af01-d13f801fc561"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Previous Track"",
                    ""type"": ""Button"",
                    ""id"": ""cca22a9d-433b-4e19-978c-8458ae00f00d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Play Radio"",
                    ""type"": ""Button"",
                    ""id"": ""ab01c9e1-b0c8-48f8-93c4-53f621f36cbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Next Track"",
                    ""type"": ""Button"",
                    ""id"": ""4701b2a6-b5fa-41e6-8537-c8809034c912"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Show Radio"",
                    ""type"": ""Button"",
                    ""id"": ""521c3e8a-bfe6-408f-98c0-ddc322f73dd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""e1c0589d-2295-4d40-8f06-d06f99ff5318"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""755644bf-1fac-49c4-9c60-b1b95ab29a1d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b8b8ddc7-b9b1-4522-a7d5-11e360041614"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""db675cb6-025f-4f90-9d6d-9d402535f225"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f4981b52-5d64-4efb-835b-2bf07a2ce131"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller"",
                    ""id"": ""13bfc549-863c-4c28-91ba-b843ffcdefe3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fcd2ef35-8dda-4661-a871-19db19149852"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cbdb721e-10c8-486e-98d4-ca7642290acd"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""855712f0-a3be-4c48-b9a0-ebabf6aeac11"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""aa463cc5-7620-4ce6-8761-042d08d00af7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""99ea56fd-fbee-45d2-8745-7bb9e73de79f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c2fac96-1791-45a6-b443-60475c317255"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d27468c-110d-4f40-93bf-c15ba191af8a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f35d977-b77d-4be7-a901-55d8dd30d3ce"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cf4926b-ff26-48f3-9cd6-17a4e1a94506"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6472e988-e2c9-4318-8045-c3c78f436354"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b244855-82f4-4073-9023-96c0e0fe7a9d"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Previous Track"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bf0c202-6d6a-4fed-bc49-7afd2a42aa4c"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Previous Track"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bd6033a-a390-431b-bacf-56f7bd309918"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Radio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffe4aebe-8220-4be7-a97f-af14e2a6395c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Radio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d825e0ea-13bd-42ff-be8d-056ee22330c3"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next Track"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8940920-0a1c-4648-9072-fb003ddfc8b7"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Show Radio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5995ada8-35d0-40a5-898c-aa77d4463dac"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Show Radio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5070a4da-05d4-4016-bea4-3adac0675370"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next Track"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Cutscene"",
            ""id"": ""87b768be-8a62-4d6a-a1b2-2b220959b321"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""dfbf1565-c0b0-4734-8f3c-6062720cbcc3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1847895c-d66a-4475-89de-3eb084ac8e46"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1564f639-6134-4d22-b106-055a94998ecd"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Shop"",
            ""id"": ""fe2097c7-dc1d-4691-be84-52b2e6aa6f22"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""9de61354-aa9a-49f8-918b-397707414e74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Previous Track"",
                    ""type"": ""Button"",
                    ""id"": ""ed2211fd-18ae-427c-a512-5eb9abb8e4f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Play Radio"",
                    ""type"": ""Button"",
                    ""id"": ""57680cfe-de5f-4b4f-ac38-ecfce2fdf46f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Next Track"",
                    ""type"": ""Button"",
                    ""id"": ""0f8e4908-a382-4035-b621-c3ffce903abb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Show Radio"",
                    ""type"": ""Button"",
                    ""id"": ""4c33a11b-45e3-4427-aa15-f171d26e604d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8250b3b9-76a2-42df-945d-4179063f58a0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88390d84-c0cf-4c4e-a83a-0243bf37e045"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0403a592-591d-40e7-b20f-0972afe4f870"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Previous Track"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""852f270b-60ce-41df-be27-7da6a9091c03"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Previous Track"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28771e75-054c-4da9-825c-8a51ff90278d"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Radio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4c58df1-ac53-4330-a1a1-086e26241e72"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Radio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ceae01c-b2a2-40da-81b6-ab1b18b798ef"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next Track"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0525018a-2ea2-442b-9d5d-c9930cc291bb"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next Track"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fc0e710-e1df-4644-a5bf-7fc7334cd27d"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Show Radio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74f5d2bb-6f80-4941-bcd7-fee45e4ffcf1"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Show Radio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Drift = m_Player.FindAction("Drift", throwIfNotFound: true);
        m_Player_Fire = m_Player.FindAction("Fire", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_PreviousTrack = m_Player.FindAction("Previous Track", throwIfNotFound: true);
        m_Player_PlayRadio = m_Player.FindAction("Play Radio", throwIfNotFound: true);
        m_Player_NextTrack = m_Player.FindAction("Next Track", throwIfNotFound: true);
        m_Player_ShowRadio = m_Player.FindAction("Show Radio", throwIfNotFound: true);
        // Cutscene
        m_Cutscene = asset.FindActionMap("Cutscene", throwIfNotFound: true);
        m_Cutscene_Pause = m_Cutscene.FindAction("Pause", throwIfNotFound: true);
        // Shop
        m_Shop = asset.FindActionMap("Shop", throwIfNotFound: true);
        m_Shop_Pause = m_Shop.FindAction("Pause", throwIfNotFound: true);
        m_Shop_PreviousTrack = m_Shop.FindAction("Previous Track", throwIfNotFound: true);
        m_Shop_PlayRadio = m_Shop.FindAction("Play Radio", throwIfNotFound: true);
        m_Shop_NextTrack = m_Shop.FindAction("Next Track", throwIfNotFound: true);
        m_Shop_ShowRadio = m_Shop.FindAction("Show Radio", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Drift;
    private readonly InputAction m_Player_Fire;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_PreviousTrack;
    private readonly InputAction m_Player_PlayRadio;
    private readonly InputAction m_Player_NextTrack;
    private readonly InputAction m_Player_ShowRadio;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Drift => m_Wrapper.m_Player_Drift;
        public InputAction @Fire => m_Wrapper.m_Player_Fire;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @PreviousTrack => m_Wrapper.m_Player_PreviousTrack;
        public InputAction @PlayRadio => m_Wrapper.m_Player_PlayRadio;
        public InputAction @NextTrack => m_Wrapper.m_Player_NextTrack;
        public InputAction @ShowRadio => m_Wrapper.m_Player_ShowRadio;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Drift.started += instance.OnDrift;
            @Drift.performed += instance.OnDrift;
            @Drift.canceled += instance.OnDrift;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @PreviousTrack.started += instance.OnPreviousTrack;
            @PreviousTrack.performed += instance.OnPreviousTrack;
            @PreviousTrack.canceled += instance.OnPreviousTrack;
            @PlayRadio.started += instance.OnPlayRadio;
            @PlayRadio.performed += instance.OnPlayRadio;
            @PlayRadio.canceled += instance.OnPlayRadio;
            @NextTrack.started += instance.OnNextTrack;
            @NextTrack.performed += instance.OnNextTrack;
            @NextTrack.canceled += instance.OnNextTrack;
            @ShowRadio.started += instance.OnShowRadio;
            @ShowRadio.performed += instance.OnShowRadio;
            @ShowRadio.canceled += instance.OnShowRadio;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Drift.started -= instance.OnDrift;
            @Drift.performed -= instance.OnDrift;
            @Drift.canceled -= instance.OnDrift;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @PreviousTrack.started -= instance.OnPreviousTrack;
            @PreviousTrack.performed -= instance.OnPreviousTrack;
            @PreviousTrack.canceled -= instance.OnPreviousTrack;
            @PlayRadio.started -= instance.OnPlayRadio;
            @PlayRadio.performed -= instance.OnPlayRadio;
            @PlayRadio.canceled -= instance.OnPlayRadio;
            @NextTrack.started -= instance.OnNextTrack;
            @NextTrack.performed -= instance.OnNextTrack;
            @NextTrack.canceled -= instance.OnNextTrack;
            @ShowRadio.started -= instance.OnShowRadio;
            @ShowRadio.performed -= instance.OnShowRadio;
            @ShowRadio.canceled -= instance.OnShowRadio;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Cutscene
    private readonly InputActionMap m_Cutscene;
    private List<ICutsceneActions> m_CutsceneActionsCallbackInterfaces = new List<ICutsceneActions>();
    private readonly InputAction m_Cutscene_Pause;
    public struct CutsceneActions
    {
        private @PlayerInputActions m_Wrapper;
        public CutsceneActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_Cutscene_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Cutscene; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CutsceneActions set) { return set.Get(); }
        public void AddCallbacks(ICutsceneActions instance)
        {
            if (instance == null || m_Wrapper.m_CutsceneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CutsceneActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(ICutsceneActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(ICutsceneActions instance)
        {
            if (m_Wrapper.m_CutsceneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICutsceneActions instance)
        {
            foreach (var item in m_Wrapper.m_CutsceneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CutsceneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CutsceneActions @Cutscene => new CutsceneActions(this);

    // Shop
    private readonly InputActionMap m_Shop;
    private List<IShopActions> m_ShopActionsCallbackInterfaces = new List<IShopActions>();
    private readonly InputAction m_Shop_Pause;
    private readonly InputAction m_Shop_PreviousTrack;
    private readonly InputAction m_Shop_PlayRadio;
    private readonly InputAction m_Shop_NextTrack;
    private readonly InputAction m_Shop_ShowRadio;
    public struct ShopActions
    {
        private @PlayerInputActions m_Wrapper;
        public ShopActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_Shop_Pause;
        public InputAction @PreviousTrack => m_Wrapper.m_Shop_PreviousTrack;
        public InputAction @PlayRadio => m_Wrapper.m_Shop_PlayRadio;
        public InputAction @NextTrack => m_Wrapper.m_Shop_NextTrack;
        public InputAction @ShowRadio => m_Wrapper.m_Shop_ShowRadio;
        public InputActionMap Get() { return m_Wrapper.m_Shop; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShopActions set) { return set.Get(); }
        public void AddCallbacks(IShopActions instance)
        {
            if (instance == null || m_Wrapper.m_ShopActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ShopActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @PreviousTrack.started += instance.OnPreviousTrack;
            @PreviousTrack.performed += instance.OnPreviousTrack;
            @PreviousTrack.canceled += instance.OnPreviousTrack;
            @PlayRadio.started += instance.OnPlayRadio;
            @PlayRadio.performed += instance.OnPlayRadio;
            @PlayRadio.canceled += instance.OnPlayRadio;
            @NextTrack.started += instance.OnNextTrack;
            @NextTrack.performed += instance.OnNextTrack;
            @NextTrack.canceled += instance.OnNextTrack;
            @ShowRadio.started += instance.OnShowRadio;
            @ShowRadio.performed += instance.OnShowRadio;
            @ShowRadio.canceled += instance.OnShowRadio;
        }

        private void UnregisterCallbacks(IShopActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @PreviousTrack.started -= instance.OnPreviousTrack;
            @PreviousTrack.performed -= instance.OnPreviousTrack;
            @PreviousTrack.canceled -= instance.OnPreviousTrack;
            @PlayRadio.started -= instance.OnPlayRadio;
            @PlayRadio.performed -= instance.OnPlayRadio;
            @PlayRadio.canceled -= instance.OnPlayRadio;
            @NextTrack.started -= instance.OnNextTrack;
            @NextTrack.performed -= instance.OnNextTrack;
            @NextTrack.canceled -= instance.OnNextTrack;
            @ShowRadio.started -= instance.OnShowRadio;
            @ShowRadio.performed -= instance.OnShowRadio;
            @ShowRadio.canceled -= instance.OnShowRadio;
        }

        public void RemoveCallbacks(IShopActions instance)
        {
            if (m_Wrapper.m_ShopActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IShopActions instance)
        {
            foreach (var item in m_Wrapper.m_ShopActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ShopActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ShopActions @Shop => new ShopActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnDrift(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnPreviousTrack(InputAction.CallbackContext context);
        void OnPlayRadio(InputAction.CallbackContext context);
        void OnNextTrack(InputAction.CallbackContext context);
        void OnShowRadio(InputAction.CallbackContext context);
    }
    public interface ICutsceneActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
    public interface IShopActions
    {
        void OnPause(InputAction.CallbackContext context);
        void OnPreviousTrack(InputAction.CallbackContext context);
        void OnPlayRadio(InputAction.CallbackContext context);
        void OnNextTrack(InputAction.CallbackContext context);
        void OnShowRadio(InputAction.CallbackContext context);
    }
}
